spring:
  application:
    name: c-expert
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always